from bitsnark.constants import PROJECT_ROOT_DIR

POSTGRES_USER = 'postgres'
POSTGRES_HOST = 'localhost'
POSTGRES_PORT = 5433  # nonstandard port to avoid conflicts with non-test postgres
POSTGRES_PASSWORD = 'testpostgres'

POSTGRES_DATABASE_ROOT = 'postgres'
POSTGRES_URL_ROOT = f'postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DATABASE_ROOT}'

POSTGRES_DATABASE_PROVER = 'bitsnark_prover_1'
POSTGRES_URL_PROVER = f'postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DATABASE_PROVER}'

POSTGRES_DATABASE_VERIFIER = 'bitsnark_verifier_1'
POSTGRES_URL_VERIFIER = f'postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DATABASE_VERIFIER}'

BITCOIN_RPC_URL = 'http://rpcuser:rpcpassword@localhost:19443'

DB_SCHEMA_FILE = PROJECT_ROOT_DIR / 'db' / 'schema.sql'